name: Docker Image CI

on:
  push:
    branches:
      - master
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: |
          docker build -t test . -f Test.Dockerfile
      - name: Build the Docker image
        run: |
          docker build -t pile.mdk.zone/mdkbackend/gifer:circle .
      - name: Push the Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }} pile.mdk.zone
          docker push pile.mdk.zone/mdkbackend/gifer:circle
